### ISSUE TITLE
timestamps

### ISSUE THREAD

**Issue by kallard1** [mdelerue/tts#1]
https://github.com/mdelerue/tts/blob/7c0d64c857b8e447a4f64b6ff2d6be3320ef3ee7/back/src/api/models/user.model.ts#L23

Si tu veux pas t'embêter a définir a chaque fois le champs de date de création / modification, tu as la possibilité d'ajouter cette petite option

```javascript
const userSchema = new Schema({
  // ... Ton schéma utilisateur...
}, {
  timestamps: true,
});
```

Il ajoutera et gérera automatiquement les champs `CreatedAt`/`UpdatedAt` :)

**Comment by mdelerue** [comment]
fix w/ 2761fca
